add support edljob
kubeflow/arena pull request #361
Opened 2020-09-02 09:15 UTC by jiaqianjing

2020-09-07 11:52 UTC, cheyang commented
/ok-to-test

2020-09-07 12:11 UTC, cheyang requested changes

2020-09-09 02:41 UTC, jiaqianjing commented on charts/etjob/templates/service.yaml
> +{{- end }}
fix

2020-09-09 02:41 UTC, jiaqianjing commented on charts/scalein/templates/scalein.yaml
> +    {{- end }}
fix

2020-09-09 02:58 UTC, jiaqianjing commented
/retest

2020-09-10 07:57 UTC, cheyang commented
/lgtm
/approve

2020-09-10 07:59 UTC, merged